export const types = {

    /**
     * auth types
     */
    'LOGIN_LOADING': 'LOGIN_LOADING',
    'LOGIN_SUCCESS': 'LOGIN_SUCCESS',
    'LOGIN_FAIL': 'LOGIN_FAIL',

    /**
     * metting types
     */
    'FETCHING_METTINGS': 'FETCHING_METTINGS',
    'FETCHING_METTINGS_SUCCESS': 'FETCHING_METTINGS_SUCCESS',
    'FETCHING_METTINGS_FAIL': 'FETCHING_METTINGS_FAIL',
    'UPDATE_SELECTED_METTING_ID': 'UPDATE_SELECTED_METTING_ID',
    'FETCHING_METTINGS_DETAILS': 'FETCHING_METTINGS_DETAILS',
    'FETCHING_METTINGS_DETAILS_SUCCESS': 'FETCHING_METTINGS_DETAILS_SUCCESS',
    'FETCHING_METTINGS_DETAILS_FAIL': 'FETCHING_METTINGS_DETAILS_FAIL',
    "CREATING_NEW_METTING": "CREATING_NEW_METTING",
    "CREATING_NEW_METTING_FAIL": "CREATING_NEW_METTING_FAIL",
    "CREATING_NEW_METTING_SUCCESS": "CREATING_NEW_METTING_SUCCESS",
    "FETCHING_METTING_STATUS": "FETCHING_METTING_STATUS",
    "FETCHING_METTING_STATUS_SUCCESS": "FETCHING_METTING_STATUS_SUCCESS",
    "FETCHING_METTING_STATUS_FAIL": "FETCHING_METTING_STATUS_FAIL",
    "CANCELLING_MEETING": "CANCELLING_MEETING",
    "CANCELLING_MEETING_SUCCESS": "CANCELLING_MEETING_SUCCESS",
    "CANCELLING_MEETING_FAIL": "CANCELLING_MEETING_FAIL",
    "RESET_METTING_STATE": "RESET_METTING_STATE",

    /**
     * trip types
     */
    "POSTING_TRIP": "POSTING_TRIP",
    "POSTING_TRIP_SUCCESS": "POSTING_TRIP_SUCCESS",
    "POSTING_TRIP_FAIL": "POSTING_TRIP_FAIL",
    "TOGGLE_REQUEST_VERIFICATION_CODE_TIMER": "TOGGLE_REQUEST_VERIFICATION_CODE_TIMER",
    "CONFIRMING_MEETING": "CONFIRMING_MEETING",
    "CONFIRMING_MEETING_SUCCESS": "CONFIRMING_MEETING_SUCCESS",
    "CONFIRMING_MEETING_FAIL": "CONFIRMING_MEETING_FAIL",
    
    /**
     * verification code types
     */
    "FETCHING_METTING_VERIFICATION_CODE": "FETCHING_METTING_VERIFICATION_CODE",
    "FETCHING_METTING_VERIFICATION_CODE_SUCCESS": "FETCHING_METTING_VERIFICATION_CODE_SUCCESS",
    "FETCHING_METTING_VERIFICATION_CODE_FAIL": "FETCHING_METTING_VERIFICATION_CODE_FAIL",

    /**
     * team locations types
     */
    "FETCHING_USERS": "FETCHING_USERS",
    "FETCHING_USERS_FAIL": "FETCHING_USERS_FAIL",
    "FETCHING_USERS_SUCCESS": "FETCHING_USERS_SUCCESS",
    "FETCHING_TEAM_LOCATIONS": "FETCHING_TEAM_LOCATIONS",
    "FETCHING_TEAM_LOCATIONS_SUCCESS": "FETCHING_TEAM_LOCATIONS_SUCCESS",
    "FETCHING_TEAM_LOCATIONS_FAIL": "FETCHING_TEAM_LOCATIONS_FAIL",

    /**
     * customer types
     */
    "FETCHING_CUSTOMERS": 'FETCHING_CUSTOMERS',
    "FETCHING_CUSTOMERS_SUCCESS": 'FETCHING_CUSTOMERS_SUCCESS',
    "FETCHING_CUSTOMERS_FAIL": 'FETCHING_CUSTOMERS_FAIL',

    /**
     * metting filters types
     */
    "UPDATE_START_DATE_FILTER": "UPDATE_START_DATE_FILTER",
    "UPDATE_END_DATE_FILTER": "UPDATE_END_DATE_FILTER",
    "UPDATE_SELECTED_DATE_FILTER": "UPDATE_SELECTED_DATE_FILTER",
    "UPDATE_SELECTED_USERS_FILTER": "UPDATE_SELECTED_USERS_FILTER",
    "UPDATE_SELECTED_STATUSES_FILTER": "UPDATE_SELECTED_STATUSES_FILTER",
    "UPDATE_USERS_FOR_FILTER": "UPDATE_USERS_FOR_FILTER",
    "UPDATE_STATUSES_FOR_FILTER": "UPDATE_STATUSES_FOR_FILTER",
    "UPDATE_IS_METTING_FILTERED_FLAG": "UPDATE_IS_METTING_FILTERED_FLAG",
    "CLEAR_FILTERS": "CLEAR_FILTERS"
};

/**
 * types of redux types
 */
export type ReduxTypes = keyof typeof types;